---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.51.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - "--args=--enable-rule=terraform_documented_variables"
